{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "kafka.configmap" . }}-metrics
  labels:
    app: "{{ template "kafka.name" . }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
data:
  jmx-kafka-prometheus.yml: |+
{{- if .Values.metrics.kafkaConfig }}
{{ toYaml .Values.metrics.kafkaConfig | indent 4 }}
{{- end }}
  jmx-zookeeper-prometheus.yaml: |+
{{- if .Values.metrics.zookeeperConfig }}
{{ toYaml .Values.metrics.zookeeperConfig | indent 4 }}
{{- end }}

{{- end }}
